# Generated by Django 3.1.7 on 2021-03-17 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('position', models.CharField(max_length=64)),
                ('description', models.TextField(max_length=1024)),
                ('picture', models.ImageField(upload_to='')),
                ('url', models.URLField()),
            ],
        ),
    ]
