# Generated by Django 3.1.7 on 2021-03-17 12:54

from django.db import migrations, models
import runner.validators


class Migration(migrations.Migration):

    dependencies = [
        ('runner', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='runner',
            name='cysbond',
            field=models.CharField(blank=True, max_length=128, validators=[runner.validators.validate_cysbond]),
        ),
        migrations.AlterField(
            model_name='runner',
            name='temperatures',
            field=models.CharField(blank=True, max_length=255, validators=[runner.validators.validate_temps]),
        ),
    ]
