# Generated by Django 3.2.3 on 2021-05-26 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('runner', '0002_auto_20210317_1254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='runner',
            name='sphere_radius',
            field=models.PositiveIntegerField(default=25),
        ),
        migrations.AlterField(
            model_name='runner',
            name='windows',
            field=models.PositiveIntegerField(default=50),
        ),
    ]
